### ISSUE TITLE
App stopped - android

### ISSUE THREAD

**Issue by rijink7** [EinfachHans/cordova-plugin-advanced-background-mode#3]
If the background mode is enabled then the app is getting closed when the app is minimized.
OS:android 10
Device :Xiomi device

**Comment by EinfachHans** [comment]
I need way more Information. How do you enable the Background Mode, what do you mean with "app is getting closed", does this behavior don't appear without the Plugin, do you have any Logs?

**Comment by EinfachHans** [comment]
Closed as two Weeks waiting for Reply
