### ISSUE TITLE
Not able to implement In ios.

### ISSUE THREAD

**Issue by rudrarakeshpaul** [EinfachHans/cordova-plugin-advanced-background-mode#4]
HI I tried to implement this plugin for ios in ionic 5. I tried my best to call the methods but not working.
Steps I followed : 

1) Install the plugin
2) Added in app module provider array
3) in App component I tried to inject the and call the function

Can you provide some sample code? it will be very helpful. We r stuck for 15 days on background issues.

sorry for my bad English.

**Comment by rudrarakeshpaul** [comment]
import BackgroundMode from 'cordova-plugin-advanced-background-mode';


export class AppComponent {
 ..................
 backgroundMode = BackgroundMode;
 ................
  
 this.platform.ready().then(() => {
   
   this.backgroundMode.enable();
      if(this.backgroundMode.isActive())
      {
        this.backgroundMode.on('activate',()=>{
          this.backgroundMode.setDefaults({ silent: true });
          this.backgroundMode.disableWebViewOptimizations(); 
        });
      }
})

}

In IOS it's not working....

**Comment by gaurav-chandra** [comment]
have you added the capability in info.plist in xcode? On ios there are configs which need to be done manually. [https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio#:~:text=Under%20the%20Capabilities%20tab%2C%20set,ready%20to%20play%20background%20audio.](https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio#:~:text=Under%20the%20Capabilities%20tab%2C%20set,ready%20to%20play%20background%20audio.)

**Comment by gaurav-chandra** [comment]
Have you enabled the settings in xcode? on ios, there are manual steps which need to be performed.
[https://www.raywenderlich.com/5817-background-modes-tutorial-getting-started](https://www.raywenderlich.com/5817-background-modes-tutorial-getting-started)

**Comment by EinfachHans** [comment]
What do you mean with `In IOS it's not working....`? Does the `on('activate')` doesn't get called?

**Comment by EinfachHans** [comment]
Closed as no Answer
