### ISSUE TITLE
(bug):Plugin not working correctly on iOS 14

### ISSUE THREAD

**Issue by mateoalleyne** [EinfachHans/cordova-plugin-advanced-background-mode#6]
# Bug Report

**Current Behavior:**

Plugin won't run a background task on iOS.
**Expected Behavior:**

The task consists of an infinite while loop that's suposed to have a 1 second pause and show the current time every 10 loops (equivalent to 10 seconds). It won't show anything in the console after the app is sent to background mode.
**Steps to reproduce:**

let cont=1
      while (true) {
      let now = new Date()
      if(cont==10){
        cont=1
        // await this.pause(1)
        console.log(now.getTime()+' '+now.toString())
      }
      else{
        cont++
      }
      await this.pause(1000)
    }

**Comment by EinfachHans** [comment]
How do you use this Plugin, what do you do to enable the Background Mode?

**Comment by mateoalleyne** [comment]
I am working on Capacitor:

import BackgroundMode from 'cordova-plugin-advanced-background-mode';

**Comment by mateoalleyne** [comment]
I am working with Capacitor:

import BackgroundMode from 'cordova-plugin-advanced-background-mode';

The function where it's started is:

initializeListener() {
document.addEventListener('deviceready', function () {
    }, false);
    BackgroundMode.enable()
BackgroundMode.on('activate',function(){
      BackgroundMode.disableBatteryOptimizations()
      BackgroundMode.disableWebViewOptimizations()
      console.log('Background mode enabled: '+BackgroundMode.isEnabled())
      this.backgroundCheck()
    })

Sorry if I use plane text instead of code format. I am very new at this and don't really know how to format the text. Thank you for your response @EinfachHans

**Comment by mateoalleyne** [comment]
> I am working with Capacitor:
> 
> import BackgroundMode from 'cordova-plugin-advanced-background-mode';
> 
> The function where it's started is:
> 
> initializeListener() {
> document.addEventListener('deviceready', function () {
> }, false);
> BackgroundMode.enable()
> BackgroundMode.on('activate',function(){
> BackgroundMode.disableBatteryOptimizations()
> BackgroundMode.disableWebViewOptimizations()
> console.log('Background mode enabled: '+BackgroundMode.isEnabled())
> this.backgroundCheck()
> })
> 
> Sorry if I use plane text instead of code format. I am very new at this and don't really know how to format the text. Thank you for your response @EinfachHans

PS: backGroundCheck is the function that contains the while loop that I posted in the previous comment

**Comment by EinfachHans** [comment]
So, i'm not using Capacitor yet. Also i did not testes this Plugin with Capacitor. I found this about Capacitor Background Tasks: https://capacitorjs.com/docs/apis/background-task

I'm using this Plugin in our main app, where i needed to do many stuff backgrounded, that's why i forked it. It works perfect there, but it is not he only one. I also use a Background Geolocation Plugin that i think do some stuff 🤔

**Comment by mateoalleyne** [comment]
> So, i'm not using Capacitor yet. Also i did not testes this Plugin with Capacitor. I found this about Capacitor Background Tasks: https://capacitorjs.com/docs/apis/background-task
> 
> I'm using this Plugin in our main app, where i needed to do many stuff backgrounded, that's why i forked it. It works perfect there, but it is not he only one. I also use a Background Geolocation Plugin that i think do some stuff 🤔

I've already tried that plugin and didn't get the result I wanted... I'll close the Issue and do a little more research. Again thanks for your time and great plugin, works great in Capacitor with Android 9!
