### ISSUE TITLE
İonic 5 use error ?

### ISSUE THREAD

**Issue by demirkolemre** [EinfachHans/cordova-plugin-advanced-background-mode#9]
Hello, can you help me?

I am using ionic 5 and angular .ı try background service app.
I can't add my project.

![image](https://user-images.githubusercontent.com/24626973/116794547-63432480-aad6-11eb-9477-84e2c261aa26.png)

**Comment by ErwannLeRoux** [comment]
Hi, 

It seems like we have to use this plugin differently from the original plugin as methods are static methods from BackgroundMode's class.

Maybe you could try using methods this way without inject it in angular constructor : 

`
import BackgroundMode from 'cordova-plugin-advanced-background-mode';
BackgroundMode.setDefaults(...);
`

Hope it helps 😄
